
import { Product, Category, Order } from './types';

export const THEME_COLOR = "emerald"; // mapped to tailwind classes
export const PRIMARY_BG = "bg-emerald-500";
export const PRIMARY_TEXT = "text-emerald-500";
export const HOVER_TEXT = "hover:text-emerald-600";
export const BTN_PRIMARY = "bg-emerald-500 hover:bg-emerald-600 text-white";

export const INITIAL_CATEGORIES: Category[] = [];

export const INITIAL_PRODUCTS: Product[] = [];

export const INITIAL_ORDERS: Order[] = [];

export const DISTRICT_AREA_DATA: Record<string, string[]> = {
  "Dhaka": [
    "60 feet",
    "Abdullahpur Uttara",
    "Abul Hotel",
    "Adabor",
    "Adarsha Nagar - Kutubpur",
    "Aftab Nagar",
    "Aganagar",
    "Agargaon",
    "Agargaon-Taltola",
    "Akran Bazar",
    "Amin Bazar",
    "Amritopur",
    "Amtola",
    "Arambag",
    "Ashkona",
    "Ashulia Bazar",
    "azampur (Uttara)",
    "Azimpur (Lalbag)",
    "Badda",
    "Baily Road",
    "Baipail",
    "Bakshi Bazar",
    "Bakurta",
    "Balughat",
    "Banani",
    "Banani DOHS",
    "banani hq",
    "Banasree (Block A-G)",
    "Banasree (Block H-J)",
    "Bangla bazar",
    "Banglamotor",
    "Bangshal",
    "Bank Colony, Savar",
    "Baridhara Diplomatic Zone",
    "Baridhara DOHS",
    "Baridhara J Block",
    "Barobaria",
    "Baroipara",
    "Bashabo",
    "Bashundhara R/A",
    "Bawnia",
    "Begunbari",
    "Benaroshi Polli",
    "Benaroshi polli Blok A",
    "Benaroshi polli Blok B,C",
    "Benaroshi polli Blok D",
    "Beraid",
    "Bibir Bagicha",
    "Block A,B, Mirpur 6",
    "Block A, C, Mirpur 11",
    "Block B, D, Mirpur 11",
    "Block D,E , Mirpur 6",
    "Block-E, Mirpur 12",
    "Bolivodro",
    "Borobag",
    "Boro Moghbazar",
    "Bosila",
    "Brahmonkitta",
    "BUET",
    "Bulk Merchant",
    "Central Road",
    "Chakraborty",
    "Charabag, Ashulia",
    "ChawkBazar (Dhaka)",
    "Chunkutia",
    "Dakshinkhan",
    "Darussalam",
    "Demra",
    "Deogao, Savar",
    "Dhaka cantonment",
    "Dhaka Medical",
    "Dhaka Uddyan",
    "Dhaka University",
    "Dhammondi",
    "Dhamrai",
    "Dhamrai , Savar",
    "Dhanmondi",
    "Dholaipar",
    "Dholpur",
    "Dhonia",
    "Dhulivita",
    "Diabari",
    "DIT Road",
    "Document-Central",
    "Dohar",
    "ECB",
    "Elephant Road",
    "EPZ",
    "Equria Thana",
    "Eskaton",
    "Estern Housing",
    "Extension Pallabi",
    "Faidabad",
    "Faridabad",
    "Farmgate",
    "Fulbariya",
    "Gabtoli",
    "Ganda, Savar",
    "Gandaria",
    "GhatarChar",
    "Giridhara Abashik",
    "Gobindopur",
    "Golam Bazar",
    "Gopibagh",
    "Goran",
    "Gulbagh",
    "Gulisthan",
    "Gulshan 1",
    "Gulshan 2",
    "Hasnabad",
    "Hatirpool",
    "Hazaribagh",
    "Hemayetpur",
    "house building",
    "Huzurbari Gate",
    "Ibrahimpur",
    "Islambag",
    "Islampur",
    "Islampur (Dhamrai)",
    "Jahangirnagar, Savar",
    "Jamgora",
    "Jhauchor",
    "Jigatola",
    "Joardar Lane",
    "Jonopoth More Bus Stop",
    "Journalist Residential Area",
    "Jurain",
    "Kadamtoli",
    "Kalabagan",
    "kalachadpur",
    "Kalampur",
    "Kalindi",
    "Kallyanpur",
    "Kamalapur",
    "Kamranggirchar",
    "Karatitola",
    "Katashur",
    "Katghora, Savar",
    "Kathalbagan",
    "Kawalipara",
    "Kawla",
    "Kawran Bazar",
    "Kazipara",
    "Keraniganj",
    "Keraniganj Abdullahpur",
    "Keraniganj Atibazar",
    "Keraniganj BoshundhoraRiverview",
    "Keraniganj Kaliganj",
    "Keraniganj Model Thana",
    "Keraniganj Rajendrapur",
    "Khejurbag",
    "Khilgaon",
    "Khilkhet",
    "Kholamura",
    "Khorarchar",
    "Kochukhet",
    "Kodomtoli.",
    "Kolatia",
    "Kolma",
    "Konakhola",
    "Konapara",
    "Kotwali (Dhaka)",
    "Kuril",
    "Kutubkhali",
    "Lakshmibazar",
    "Lalbag",
    "Lalkuthi",
    "Lalmatia",
    "LaxmiBazar",
    "london market",
    "Love Road, Mirpur-2",
    "Madani nagar",
    "Malibagh Baganbari",
    "Malibagh College Road",
    "Malibagh Lane",
    "Malibagh Pabna Colony",
    "Maloncho Road",
    "Manda",
    "Manik Nagar",
    "Manikdi",
    "Masjid Market",
    "Matikata",
    "Matuail",
    "Mazar road",
    "Middle Rosulbag",
    "Mirhazirbag",
    "Mirpur 1",
    "Mirpur 1 Market Area",
    "Mirpur 10",
    "Mirpur 11",
    "Mirpur 11 Lalmatia",
    "Mirpur 12",
    "Mirpur 12 Block A,C",
    "Mirpur 12 Block Ta",
    "Mirpur 12 Block-Dhak, B",
    "Mirpur 13",
    "Mirpur 14",
    "Mirpur 2",
    "Mirpur 6",
    "Mirpur 6 (Block C)",
    "Mirpur 7",
    "Mirpur Cantonment",
    "Mirpur Cantonment (Ave new 3 )",
    "Mirpur DOHS",
    "Mirpur DOHS (Ave new 2)",
    "Mirpur DOHS (Ave New 9)",
    "Mirpur-Rupnagar",
    "Modhubag",
    "Mogbazar",
    "Mohakhali",
    "Mohakhali DOHS",
    "Mohammadpur",
    "Monipur",
    "Monumia Market",
    "Motijheel",
    "Mugda",
    "mukti nagar",
    "Nadda",
    "Nakhal para",
    "Nakhalpara",
    "narayanpur - keshobpur",
    "Narinda",
    "Nawabganj (Dhaka)",
    "Nawabganj (Dohar)",
    "Nawabpur",
    "Naya Bazar",
    "Nayanagar",
    "Nazim Uddin Road",
    "Nazira Bazar",
    "New Elephant Road",
    "New Market",
    "new paltan azimpur",
    "New Town R/A",
    "Niketan",
    "Nikunja",
    "Nikunja 2",
    "Nilkhet",
    "Nimaikishori",
    "Nischintapur",
    "Nobinagar",
    "Nobodoy",
    "Norosinhopur",
    "North Badda",
    "North Sanarpar",
    "Notun Bazar",
    "Noyarhat",
    "Noyatola road",
    "Nurerchala",
    "Paikpara",
    "Pakiza, Savar",
    "Pallabi",
    "Pallabi Residential area",
    "Palli Bidyut",
    "Paltan",
    "Panthapath",
    "Paterbag",
    "Pathao Central FTL",
    "Pathao Central LTL",
    "Pirerbagh",
    "Polashbari",
    "Polashpur",
    "Radio Colony, Savar",
    "Rajashon, Savar",
    "rajlakkhi market",
    "Rampura",
    "ranavola",
    "Rayer Bazar",
    "Rayerbag",
    "Razarbag Police line",
    "Rohitpur",
    "Rupnagar",
    "Sadarghat (Dhaka)",
    "Saddam Market",
    "Sarkar Market",
    "Savar Bazar",
    "Savar Thana Road",
    "Savar-Nabinagar",
    "Saydabad",
    "Sayedabad Bus Terminal",
    "Senpara",
    "Senpara Parbata",
    "Shagufta Block-D",
    "Shah Ali Bag",
    "Shahbag",
    "Shahid Faruk Road",
    "Shahid Nagar",
    "Shahjadpur",
    "Shajahanpur",
    "shampur",
    "Shanir Akhra",
    "shankar",
    "Shantinagar",
    "Shegunbagicha",
    "Sheikh Rasel Park",
    "Sheikhdi",
    "Sher-e Bangla Nagar",
    "Sher-E-Bangla National Cricket Stadium",
    "Shewrapara",
    "Shiddeshwari",
    "Shimrail",
    "Shimultola Jamgora",
    "Shimultola, Savar",
    "Shishu Mela",
    "Shobujbag",
    "Shonalibagh",
    "Shukrabad",
    "Shuvadda",
    "Shyamoli",
    "Singair Road",
    "Solmaid",
    "SONY Cinema Hall",
    "South Badda",
    "South Banasree",
    "South kafrul",
    "Sreepur-Kashimpur",
    "Sutrapur",
    "Technical",
    "Tejgaon",
    "Tejkunipara",
    "Tenari Savar",
    "Tolarbag",
    "Turag",
    "Unique Bus Stand",
    "Uttara Sector 1",
    "Uttara Sector 10",
    "Uttara Sector 11",
    "Uttara Sector 12",
    "Uttara Sector 13",
    "Uttara Sector 14",
    "Uttara Sector 15",
    "Uttara Sector 16",
    "Uttara Sector 17",
    "Uttara Sector 18",
    "Uttara Sector 3",
    "Uttara Sector 4",
    "Uttara Sector 5",
    "Uttara sector 6",
    "Uttara Sector 7",
    "Uttara Sector 8",
    "Uttara Sector 9",
    "UttarKhan",
    "Vadail",
    "Vasan Tek",
    "Vootergoli",
    "Wari",
    "West Agargaon",
    "West Kafrul",
    "Zazira",
    "Zinzira",
    "Zirabo",
    "Zirani",
    "Zoo Road"
  ].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base', numeric: true })),
  "Bagerhat": ["Bagerhat Sadar", "Chitalmari", "Fakirhat", "Kachua", "Mollahat", "Mongla", "Morrelganj", "Rampal", "Sarankhola"].sort(),
  "Bandarban": ["Alikadam", "Bandarban Sadar", "Lama", "Naikhongchhari", "Rowangchhari", "Ruma", "Thanchi"].sort(),
  "Barguna": ["Amtali", "Bamna", "Barguna Sadar", "Betagi", "Patharghata", "Taltali"].sort(),
  "Barisal": ["Agailjhara", "Babuganj", "Bakerganj", "Banaripara", "Barisal Sadar", "Gournadi", "Hizla", "Mehendiganj", "Muladi", "Wazirpur"].sort(),
  "Bhola": ["Bhola Sadar", "Borhan Uddin", "Charfesson", "Daulatkhan", "Lalmohan", "Monpura", "Tazumuddin"].sort(),
  "Bogura": ["Adamdighi", "Bogra Sadar", "Dhunot", "Dupchanchia", "Gabtali", "Kahaloo", "Nandigram", "Shajahanpur", "Shariakandi", "Sherpur", "Shibganj", "Sonatala"].sort(),
  "Brahmanbaria": ["Akhaura", "Ashuganj", "Bancharampur", "Bijoynagar", "Brahmanbaria Sadar", "Kasba", "Nabinagar", "Nasirnagar", "Sarail"].sort(),
  "Chandpur": ["Chandpur Sadar", "Faridgonj", "Haimchar", "Hajiganj", "Kachua", "Matlab North", "Matlab South", "Shahrasti"].sort(),
  "Chapainawabganj": ["Bholahat", "Chapainawabganj Sadar", "Gomostapur", "Nachol", "Shibganj"].sort(),
  "Chattogram": ["Anwara", "Banshkhali", "Boalkhali", "Chandanaish", "Fatickchhari", "Hathazari", "Karnaphuli", "Lohagara", "Mirsharai", "Patiya", "Rangunia", "Raozan", "Sandwip", "Satkania", "Sitakunda"].sort(),
  "Chuadanga": ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"].sort(),
  "Comilla": ["Barura", "Brahmanpara", "Burichang", "Chandina", "Chauddagram", "Comilla Sadar", "Daudkandi", "Debidwar", "Homna", "Laksam", "Lalmai", "Meghna", "Monohargonj", "Muradnagar", "Nangalkot", "Sadarsouth", "Titas"].sort(),
  "Coxsbazar": ["Chakaria", "Coxsbazar Sadar", "Kutubdia", "Maheshkhali", "Pekua", "Ramu", "Teknaf", "Ukhiya"].sort(),
  "Dinajpur": ["Birol", "Birampur", "Birganj", "Bochaganj", "Chirirbandar", "Dinajpur Sadar", "Fulbari", "Ghoraghat", "Hakimpur", "Kaharol", "Khansama", "Nawabganj", "Parbatipur"].sort(),
  "Faridpur": ["Alfadanga", "Bhanga", "Boalmari", "Charbhadrasan", "Faridpur Sadar", "Madhukhali", "Nagarkanda", "Sadarpur", "Saltha"].sort(),
  "Feni": ["Chhagalnaiya", "Daganbhuiyan", "Feni Sadar", "Fulgazi", "Parshuram", "Sonagazi"].sort(),
  "Gaibandha": ["Gaibandha Sadar", "Gobindaganj", "Palashbari", "Phulchari", "Sadullapur", "Saghata", "Sundarganj"].sort(),
  "Gazipur": ["Gazipur Sadar", "Kaliganj", "Kaliakair", "Kapasia", "Sreepur"].sort(),
  "Gopalganj": ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"].sort(),
  "Habiganj": ["Ajmiriganj", "Bahubal", "Baniachong", "Chunarughat", "Habiganj Sadar", "Lakhai", "Madhabpur", "Nabiganj"].sort(),
  "Jamalpur": ["Bakshiganj", "Dewanganj", "Islampur", "Jamalpur Sadar", "Madarganj", "Melandah", "Sarishabari"].sort(),
  "Jashore": ["Abhaynagar", "Bagherpara", "Chougachha", "Jessore Sadar", "Jhikargacha", "Keshabpur", "Manirampur", "Sharsha"].sort(),
  "Jhalakathi": ["Jhalakathi Sadar", "Kathalia", "Nalchity", "Rajapur"].sort(),
  "Jhenaidah": ["Harinakundu", "Jhenaidah Sadar", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"].sort(),
  "Joypurhat": ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"].sort(),
  "Khagrachhari": ["Dighinala", "Guimara", "Khagrachhari Sadar", "Laxmichhari", "Manikchari", "Matiranga", "Mohalchari", "Panchari", "Ramgarh"].sort(),
  "Khulna": ["Botiaghata", "Dakop", "Digholia", "Dumuria", "Fultola", "Koyra", "Paikgasa", "Rupsha", "Terokhada"].sort(),
  "Kishoreganj": ["Austagram", "Bajitpur", "Bhairab", "Hossainpur", "Itna", "Karimgonj", "Katiadi", "Kishoreganj Sadar", "Kuliarchar", "Mithamoin", "Nikli", "Pakundia", "Tarail"].sort(),
  "Kurigram": ["Charrajibpur", "Chilmari", "Kurigram Sadar", "Nageshwari", "Phulbari", "Rajarhat", "Rowmari", "Ulipur"].sort(),
  "Kushtia": ["Bheramara", "Daulatpur", "Khoksa", "Kumarkhali", "Kushtia Sadar", "Mirpur"].sort(),
  "Lakshmipur": ["Kamalnagar", "Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati"].sort(),
  "Lalmonirhat": ["Aditmari", "Hatibandha", "Kaliganj", "Lalmonirhat Sadar", "Patgram"].sort(),
  "Madaripur": ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"].sort(),
  "Magura": ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"].sort(),
  "Manikganj": ["Daulatpur", "Gior", "Harirampur", "Manikganj Sadar", "Saturia", "Shibaloy", "Singair"].sort(),
  "Meherpur": ["Gangni", "Meherpur Sadar", "Mujibnagar"].sort(),
  "Moulvibazar": ["Barlekha", "Juri", "Kamalganj", "Kulaura", "Moulvibazar Sadar", "Rajnagar", "Sreemangal"].sort(),
  "Munshiganj": ["Gajaria", "Louhajanj", "Munshiganj Sadar", "Sirajdikhan", "Sreenagar", "Tongibari"].sort(),
  "Mymensingh": ["Bhaluka", "Dhobaura", "Fullbaria", "Gafargaon", "Gauripur", "Haluaghat", "Iswarganj", "Muktagacha", "Mymensingh Sadar", "Nandail", "Phulpur", "Tarakanda", "Trishal"].sort(),
  "Naogaon": ["Atrai", "Badalgachhi", "Dhamoirhat", "Manda", "Mohadevpur", "Naogaon Sadar", "Niamatpur", "Patnitala", "Porsha", "Raninagar", "Sapahar"].sort(),
  "Narail": ["Kalia", "Lohagara", "Narail Sadar"].sort(),
  "Narayanganj": ["Araihazar", "Bandar", "Narayanganj Sadar", "Rupganj", "Sonargaon"].sort(),
  "Narsingdi": ["Belabo", "Monohardi", "Narsingdi Sadar", "Palash", "Raipura", "Shibpur"].sort(),
  "Natore": ["Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Naldanga", "Natore Sadar", "Singra"].sort(),
  "Netrokona": ["Atpara", "Barhatta", "Durgapur", "Kalmakanda", "Kendua", "Khaliajuri", "Madan", "Mohongonj", "Netrokona Sadar", "Purbadhala"].sort(),
  "Nilphamari": ["Dimla", "Domar", "Jaldhaka", "Kishorganj", "Nilphamari Sadar", "Syedpur"].sort(),
  "Noakhali": ["Begumganj", "Chatkhil", "Companiganj", "Hatia", "Kabirhat", "Noakhali Sadar", "Senbug", "Sonaimori", "Subarnachar"].sort(),
  "Pabna": ["Atghoria", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishurdi", "Pabna Sadar", "Santhia", "Sujanagar"].sort(),
  "Panchagarh": ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"].sort(),
  "Patuakhali": ["Bauphal", "Dashmina", "Dumki", "Galachipa", "Kalapara", "Mirzaganj", "Patuakhali Sadar", "Rangabali"].sort(),
  "Pirojpur": ["Bhandaria", "Kawkhali", "Mathbaria", "Nazirpur", "Nesarabad", "Pirojpur Sadar", "Zianagar"].sort(),
  "Rajbari": ["Baliakandi", "Goalanda", "Kalukhali", "Pangsa", "Rajbari Sadar"].sort(),
  "Rajshahi": ["Bagha", "Bagmara", "Charghat", "Durgapur", "Godagari", "Mohonpur", "Paba", "Puthia", "Tanore"].sort(),
  "Rangamati": ["Baghaichari", "Barkal", "Belaichari", "Juraichari", "Kaptai", "Kawkhali", "Langadu", "Naniarchar", "Rajasthali", "Rangamati Sadar"].sort(),
  "Rangpur": ["Badargonj", "Gangachara", "Kaunia", "Mithapukur", "Pirgacha", "Pirgonj", "Rangpur Sadar", "Taragonj"].sort(),
  "Satkhira": ["Assasuni", "Debhata", "Kaliganj", "Kalaroa", "Satkhira Sadar", "Shyamnagar", "Tala"].sort(),
  "Shariatpur": ["Bhedarganj", "Damudya", "Gosairhat", "Naria", "Shariatpur Sadar", "Zajira"].sort(),
  "Sherpur": ["Jhenaigati", "Nalitabari", "Nokla", "Sherpur Sadar", "Sreebordi"].sort(),
  "Sirajganj": ["Belkuchi", "Chauhali", "Kamarkhand", "Kazipur", "Raigonj", "Shahjadpur", "Sirajganj Sadar", "Tarash", "Ullapara"].sort(),
  "Sunamganj": ["Bishwambarpur", "Chhatak", "Derai", "Dharmapasha", "Dowarabazar", "Jagannathpur", "Jamalganj", "Shalla", "South Sunamganj", "Sunamganj Sadar", "Tahirpur"].sort(),
  "Sylhet": ["Balaganj", "Beanibazar", "Bishwanath", "Companiganj", "Dakshinsurma", "Fenchuganj", "Golapganj", "Gowainghat", "Jaintiapur", "Kanaighat", "Osmaninagar", "Sylhet Sadar", "Zakiganj"].sort(),
  "Tangail": ["Basail", "Bhuapur", "Delduar", "Dhanbari", "Ghatail", "Gopalpur", "Kaliati", "Madhupur", "Mirzapur", "Nagarpur", "Sakhipur", "Tangail Sadar"].sort(),
  "Thakurgaon": ["Baliadangi", "Haripur", "Pirganj", "Ranisankail", "Thakurgaon Sadar"].sort()
};
